name: project-version

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: echo '//registry.npmjs.org/:_authToken=${{ secrets.ISYSCORE_NPM_TOKEN }}' > .npmrc
      - run: npm publish --access=public --registry=https://registry.npmjs.org

  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: git_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GIT_VERSION: ${{ steps.git_tag.outputs.VERSION }}
        with:
          tag_name: ${{ env.GIT_VERSION }}
          release_name: Release ${{ env.GIT_VERSION }}
          draft: false
          prerelease: false
          body: "[${{ env.GIT_VERSION }} changelog](https://github.com/${{ github.repository }}/blob/${{ env.GIT_VERSION }}/CHANGELOG.md)"

